site_name: Phable
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    # - content.code.annotation
    # ^ should this be content.code.annotate?  Not sure if needed for now
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
repo_name: phable
repo_url: https://github.com/rick-jennings/phable
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          # merge_init_into_class: true
          # docstring_options:
          #   ignore_init_summary: true
          annotations_path: full
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_docstring_raises: true
          # show_docstring_description: true
          # show_signature_annotations: true
