site_name: Phable
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    # - content.code.annotation
    # ^ should this be content.code.annotate?  Not sure if needed for now
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
repo_name: phable
repo_url: https://github.com/rick-jennings/phable
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          annotations_path: full
          merge_init_into_class: false
          # signature_crossrefs: true
          # ^ this might not do anything since Annotations are not used
          show_symbol_type_heading: true
          show_symbol_type_toc: true